# Generated by Django 4.2.10 on 2024-03-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('position_title', models.CharField(max_length=100)),
                ('affiliation_institution', models.CharField(max_length=100)),
                ('research_interests', models.TextField()),
                ('degree_sought', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_degree_date', models.DateField(blank=True, null=True)),
                ('countries_of_research_focus', models.ManyToManyField(to='myapp.country')),
            ],
        ),
    ]
