# Generated by Django 4.2.10 on 2024-03-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20240311_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
