# Generated by Django 4.2.10 on 2024-03-22 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0006_alter_researcher_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('century', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('other', models.TextField(blank=True)),
                ('CE_or_BCE', models.CharField(blank=True, choices=[('CE', 'CE'), ('BCE', 'BCE')], max_length=3)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('source', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='research_images/')),
                ('file', models.FileField(blank=True, null=True, upload_to='research_files/')),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.country')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
